#!/usr/bin/bash

image=missionsystems/hyperteaming:detection
name=detr_model_builder
docker run -it -d --gpus all --privileged \
	-e NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility,display \
	--name $name \
	--user devops \
	-v $HOME/src/hyperteaming/detr:/home/devops/src/hyperteaming/detr \
	$image tail -f /dev/null 

docker exec $name /bin/bash -c "cd /home/devops/src/hyperteaming/detr/src; python3 build_model.py --w 1024 --h 800 --num_classes 3 --checkpoint '../detr/outputs/3classes_res101_cpt1630.pth'"
docker exec $name /bin/bash -c "cd /home/devops/src/hyperteaming/detr/src; python3 serialise_engine.py --max_batch_size 1"

docker stop $name
docker rm $name
